USE DATABASE MOVIELENS;
CREATE SCHEMA RAW_M;
-----------------------------------------------------------------
--STORAGE integration
-----------------------------------------------------------------

create or replace storage integration PROJECT_DI_INTEGRATION
type = EXTERNAL_STAGE
storage_provider = S3
enabled = TRUE
storage_aws_role_arn = 'arn:aws:iam::72155911111111:role/project_role'
storage_allowed_locations= ('s3://diprojectdatas/');

DESC INTEGRATION PROJECT_DI_INTEGRATION;

--------------------------------------------------------------
--NOTIFICATION INTEGRATION
--------------------------------------------------------------


CREATE or replace NOTIFICATION INTEGRATION PIPE_NOTIFICATION_NETFLIX
ENABLED = true  
TYPE = QUEUE
NOTIFICATION_PROVIDER = AWS_SNS  
DIRECTION = OUTBOUND
AWS_SNS_TOPIC_ARN = 'arn:aws:sns:us-east-1:72155911111111:project_di_topic'  
AWS_SNS_ROLE_ARN = 'arn:aws:iam::72155911111111:role/sns_role';

DESC NOTIFICATION INTEGRATION PIPE_NOTIFICATION;





--Bucket Name -- netflixbucket85


create or replace storage integration AWS_S3_NETFLIX_INT
type = EXTERNAL_STAGE
storage_provider = S3
enabled = TRUE
storage_aws_role_arn = 'arn:aws:iam::72155911111111:role/Nexflix_Dbt_Role'
storage_allowed_locations= ('s3://movielen/');


DESC INTEGRATION AWS_S3_NETFLIX_INT;

CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT_NETFLIX
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'


CREATE OR REPLACE STAGE netflixstage_movies
URL='s3://movielen/csv/movies/'
storage_integration = AWS_S3_NETFLIX_INT
FILE_FORMAT = 'CSV_FILE_FORMAT_NETFLIX';


-- Load raw_movies
CREATE OR REPLACE TABLE raw_movies (
movieId INTEGER,
title STRING,
genres STRING,
load_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE OR REPLACE PIPE MOVIE_PIPE  
AUTO_INGEST = TRUE
--ERROR_INTEGRATION = PIPE_NOTIFICATION  
AS
COPY INTO MOVIELENS.RAW_M.RAW_MOVIES 
FROM 
(
	SELECT
		T.$1 AS RMV_MOVIE_ID,  
		T.$2 AS RMV_TITLE,
		T.$3 AS RMV_GENRES,
		CURRENT_TIMESTAMP AS RMV_LOAD_TIME  
	FROM @netflixstage_movies T
)
FILE_FORMAT = 'CSV_FILE_FORMAT_NETFLIX';



CREATE OR REPLACE STAGE netflixstage_ratings
URL='s3://movielen/csv/ratings/'
storage_integration = AWS_S3_NETFLIX_INT
FILE_FORMAT = 'CSV_FILE_FORMAT_NETFLIX';


-- Load RAW_RATINGS
CREATE OR REPLACE TABLE RAW_RATINGS (
userId INTEGER,
movieId INTEGER,
rating FLOAT,
load_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE PIPE RATING_PIPE  
AUTO_INGEST = TRUE
--ERROR_INTEGRATION = PIPE_NOTIFICATION  
AS
COPY INTO MOVIELENS.RAW_M.RAW_RATINGS 
FROM 
(
	SELECT
		T.$1 AS RRR_USER_ID,  
		T.$2 AS RRT_MOVIE_ID,
		T.$3 AS RRT_RATING,
		CURRENT_TIMESTAMP AS RRT_LOAD_TIME  
	FROM @netflixstage_ratings T
)
FILE_FORMAT = 'CSV_FILE_FORMAT_NETFLIX';


CREATE OR REPLACE STAGE netflixstage_tags
URL='s3://movielen/csv/tags/'
storage_integration = AWS_S3_NETFLIX_INT
FILE_FORMAT = 'CSV_FILE_FORMAT_NETFLIX';


-- Load RAW_RATINGS
CREATE OR REPLACE TABLE RAW_TAGS (
userId INTEGER,
movieId INTEGER,
tag STRING,
load_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE OR REPLACE PIPE TAG_PIPE  
AUTO_INGEST = TRUE
--ERROR_INTEGRATION = PIPE_NOTIFICATION  
AS
COPY INTO MOVIELENS.RAW_M.RAW_TAGS 
FROM 
(
	SELECT
		T.$1 AS RT_USER_ID,  
		T.$2 AS RT_MOVIE_ID,
		T.$3 AS RT_TAG,
		CURRENT_TIMESTAMP AS RRT_LOAD_TIME  
	FROM @netflixstage_tags T
)
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';




CREATE OR REPLACE STAGE netflixstage_genome_scores
URL='s3://movielen/csv/genome-scores/'
storage_integration = AWS_S3_NETFLIX_INT
FILE_FORMAT = 'CSV_FILE_FORMAT_NETFLIX';


-- Load RAW_RATINGS
CREATE OR REPLACE TABLE RAW_GENOME_SCORES (
movieId INTEGER,
tagId INTEGER,
relevance FLOAT,
load_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE OR REPLACE PIPE GENOME_SCORE_PIPE  
AUTO_INGEST = TRUE
--ERROR_INTEGRATION = PIPE_NOTIFICATION  
AS
COPY INTO MOVIELENS.RAW_M.RAW_GENOME_SCORES
FROM 
(
	SELECT
		T.$1 AS RGS_MOVIE_ID,  
		T.$2 AS RGS_TAG_ID,
		T.$3 AS RGS_RELEVANCE,
		CURRENT_TIMESTAMP AS RGS_LOAD_TIME  
	FROM @netflixstage_genome_scores T
)
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');



CREATE OR REPLACE STAGE netflixstage_genome_tags
URL='s3://movielen/csv/genome-tags/'
storage_integration = AWS_S3_NETFLIX_INT
FILE_FORMAT = 'CSV_FILE_FORMAT_NETFLIX';


-- Load RAW_RATINGS
CREATE OR REPLACE TABLE RAW_GENOME_TAGS (
tagId INTEGER,
tag STRING,
load_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE OR REPLACE PIPE GENOME_TAGS_PIPE  
AUTO_INGEST = TRUE
--ERROR_INTEGRATION = PIPE_NOTIFICATION  
AS
COPY INTO MOVIELENS.RAW_M.RAW_GENOME_TAGS
FROM 
(
	SELECT 
		T.$1 AS RGT_TAG_ID,
		T.$2 AS RGT_TAG,
		CURRENT_TIMESTAMP AS RGT_LOAD_TIME  
	FROM @netflixstage_genome_tags T
)
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');





CREATE OR REPLACE STAGE netflixstage_links
URL='s3://movielen/csv/links/'
storage_integration = AWS_S3_NETFLIX_INT
FILE_FORMAT = 'CSV_FILE_FORMAT_NETFLIX';


-- Load RAW_RATINGS
CREATE OR REPLACE TABLE RAW_LINKS (
movieId INTEGER,
imdbId INTEGER,
tmdbId INTEGER,
load_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE OR REPLACE PIPE LINK_PIPE  
AUTO_INGEST = TRUE
--ERROR_INTEGRATION = PIPE_NOTIFICATION  
AS
COPY INTO MOVIELENS.RAW_M.RAW_LINKS
FROM 
(
	SELECT 
		T.$1 AS RL_MOVIE_ID,
		T.$2 AS RL_IMDB_ID,
        T.$3 AS RL_TMDB_ID,        
		CURRENT_TIMESTAMP AS RL_LOAD_TIME  
	FROM @netflixstage_links T
)
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');


show pipes;


SELECT SYSTEM$PIPE_STATUS('MOVIE_PIPE');
SELECT SYSTEM$PIPE_STATUS('GENOME_SCORE_PIPE');
SELECT SYSTEM$PIPE_STATUS('GENOME_TAGS_PIPE');
SELECT SYSTEM$PIPE_STATUS('LINK_PIPE');
SELECT SYSTEM$PIPE_STATUS('RATING_PIPE');
SELECT SYSTEM$PIPE_STATUS('TAG_PIPE');

SELECT SYSTEM$PIPE_FORCE_RESUME('MOVIE_PIPE');
SELECT SYSTEM$PIPE_FORCE_RESUME('GENOME_SCORE_PIPE');
SELECT SYSTEM$PIPE_FORCE_RESUME('GENOME_TAGS_PIPE');
SELECT SYSTEM$PIPE_FORCE_RESUME('LINK_PIPE');
SELECT SYSTEM$PIPE_FORCE_RESUME('RATING_PIPE');
SELECT SYSTEM$PIPE_FORCE_RESUME('TAG_PIPE');


ALTER PIPE MOVIE_PIPE REFRESH;
ALTER PIPE GENOME_SCORE_PIPE REFRESH;
ALTER PIPE GENOME_TAGS_PIPE REFRESH;
ALTER PIPE LINK_PIPE REFRESH;
ALTER PIPE RATING_PIPE REFRESH;
ALTER PIPE TAG_PIPE REFRESH;


select count(*) from raw_movies
union
select count(*) from raw_tags
union
select count(*) from raw_links
union
select count(*) from raw_genome_scores
union
select count(*) from raw_genome_tags
union
select count(*) from raw_ratings;








